version: '3'

services:
  nginx:
    image: nginx
    ports:
      - 8080:80
    volumes:
      - ./application:/application
      - ./congressus.conf:/etc/nginx/conf.d/default.conf
    links:
      - congressus

  congressus:
    image: congressus:0.7-fpm
    build:
        context: .
        dockerfile: Dockerfile
    volumes:
      - ./application:/application
    links:
      - memcached

  mariadb:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: congressus

  memcached:
    image: memcached:1.6-alpine

